version: "3.5"
services:
  postgres:
      container_name: pg_container
      image: postgres:15.1-alpine
      environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=root
      volumes:
        - /var/lib/postgresql/data/
      ports:
        - "5432:5432"

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
