version: '3.1'

services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:example@localhost:27017
      PORT_MAIN: 5050
      ORDERS_URL: orders:8080
  
  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - users

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
