version: "3.5"
services:
  postgres:
      container_name: pg_container
      image: postgres:15.1-alpine
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=users_service
      volumes:
        - pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - go_network

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=noemail@noemail.com
        - PGADMIN_DEFAULT_PASSWORD=root
      ports:
        - "5050:80"
      networks:
          - go_network

  users_service:
    container_name: go_users_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - go_network

  migrate:
    image: migrate/migrate
    networks:
      - go_network
    volumes:
      - ./migrations:/migrations
    command:  migrate -path ./migrations -database "postgresql://root:root@pg_container:5432/users_service?sslmode=disable" -verbose up
     # [ "-path", "/database", "-database",  "postgresql://root:root@pg_container:5432/users_service?sslmode=disable", "up" ]
    links:
      - postgres
    depends_on:
      - postgres

networks:
  go_network:
    driver: bridge

volumes:
  pgdata: